export type Badge =
  | 'ATELIER BLEND'
  | 'HANDMADE'
  | 'GOLD SERIES'
  | 'LIMITED EDITION'
  | 'PROFESSIONAL'
  | 'ORGANIC';

export type CategoryKey =
  | 'kuvertur'
  | 'dolgu-ganaj'
  | 'sos'
  | 'damla-cikolata'
  | 'vermicelli'
  | 'parca-kirintı'
  | 'drajeler'
  | 'special';

export interface Product {
  id: string;
  name: string;
  slug: string;
  category: CategoryKey;
  subcategory: string;
  badge: Badge;
  shortDescription: string;
  detailedDescription: string;
  cocoaContent?: string;
  weight: string[];
  usageArea: string;
  highlights: string[];
  image: string;
  images?: string[];
  featured: boolean;
  seoDescription: string;
}

export interface Category {
  key: CategoryKey;
  label: string;
  description: string;
}

export const CATEGORIES: Record<CategoryKey, Category> = {
  kuvertur: {
    key: 'kuvertur',
    label: 'Kuvertür',
    description: 'Profesyonel kuvertür çeşitleri ve özel harmanlamalar',
  },
  'dolgu-ganaj': {
    key: 'dolgu-ganaj',
    label: 'Sürülebilir',
    description: 'Çikolata kreması ve pralin çeşitleri',
  },
  sos: {
    key: 'sos',
    label: 'Soslar',
    description: 'Dondurma ve waffle servisine özel sos çeşitleri',
  },
  'damla-cikolata': {
    key: 'damla-cikolata',
    label: 'Damla Çikolata',
    description: 'Çeşitli çikolata damlaları',
  },
  vermicelli: {
    key: 'vermicelli',
    label: 'Vermicelli',
    description: 'Sütlü, bitter, fildişi ve frambuaz vermicelli çeşitleri',
  },
  'parca-kirintı': {
    key: 'parca-kirintı',
    label: 'Parça / Kırıntı Çikolata',
    description: 'Tatlı ve pasta yapımına özel çikolata parça ve kırıntıları',
  },
  drajeler: {
    key: 'drajeler',
    label: 'Drajeler',
    description: 'Renkli ve lezzetli drajelerimiz',
  },
  special: {
    key: 'special',
    label: 'Special Ürünler',
    description: 'Özel seçilmiş premium ürünler',
  },
};

// ═══════════════════════════════════════════════════════════════════
// KUVERTÜR (6 products)
// ═══════════════════════════════════════════════════════════════════

export const KUVERTUR_PRODUCTS: Product[] = [
  {
    id: 'kuv-001',
    name: 'Bitter Kuvertür %70',
    slug: 'bitter-kuvertur-70',
    category: 'kuvertur',
    subcategory: 'Bitter',
    badge: 'PROFESSIONAL',
    shortDescription: '%70 kakao içerikli profesyonel bitter kuvertür',
    detailedDescription:
      'Yüksek kakao oranıyla derin ve yoğun lezzet profili sunan, kaplama ve ganaj üretiminde yaygın kullanılan profesyonel bitter kuvertür.',
    cocoaContent: '%70',
    weight: ['2.5kg', '5kg', '25kg'],
    usageArea: 'Kaplama, Ganaj, Tablet Üretimi',
    highlights: ['%70 Kakao', 'Kolay Temperleme', 'Profesyonel Kullanım'],
    image: '/images/kuvertür/bitter_kovertur.png',
    featured: true,
    seoDescription: '%70 bitter kuvertür, profesyonel çikolata üretimi için',
  },
  {
    id: 'kuv-002',
    name: 'Sütlü Kuvertür %38',
    slug: 'sutlu-kuvertur-38',
    category: 'kuvertur',
    subcategory: 'Sütlü',
    badge: 'PROFESSIONAL',
    shortDescription: '%38 kakao içerikli kremsi sütlü kuvertür',
    detailedDescription:
      'Dengeli kakao ve süt oranıyla kremsi bir tekstür sunan, geniş kullanım alanına sahip sütlü kuvertür.',
    cocoaContent: '%38',
    weight: ['2.5kg', '5kg', '25kg'],
    usageArea: 'Kaplama, Pralin, Mousse',
    highlights: ['%38 Kakao', 'Kremsi Yapı', 'Geniş Kullanım Alanı'],
    image: '/images/kuvertür/sutlu_kovertur.png',
    featured: true,
    seoDescription: '%38 sütlü kuvertür, kremsi tekstürlü çikolata',
  },
  {
    id: 'kuv-003',
    name: 'Beyaz Kuvertür %35',
    slug: 'beyaz-kuvertur-35',
    category: 'kuvertur',
    subcategory: 'Beyaz',
    badge: 'PROFESSIONAL',
    shortDescription: '%35 kakao yağı içerikli beyaz kuvertür',
    detailedDescription:
      'Saf kakao yağı bazlı, vanilya aromalı ve nötr lezzet profiliyle renklendirme ve kaplama işlemlerine uygun profesyonel beyaz kuvertür.',
    cocoaContent: '%35 Kakao Yağı',
    weight: ['2.5kg', '5kg', '10kg'],
    usageArea: 'Kaplama, Dekorasyon, Ganaj',
    highlights: ['Saf Kakao Yağı', 'Vanilya Aromalı', 'Renklendirmeye Uygun'],
    image: '/images/kuvertür/beyaz_kovertur.png',
    featured: true,
    seoDescription: 'Beyaz kuvertür, saf kakao yağı bazlı',
  },
  {
    id: 'kuv-004',
    name: 'Ruby Kuvertür %47',
    slug: 'ruby-kuvertur-47',
    category: 'kuvertur',
    subcategory: 'Ruby',
    badge: 'GOLD SERIES',
    shortDescription: 'Doğal pembe renkli ruby kuvertür',
    detailedDescription:
      'Boyasız, doğal işlem yöntemiyle elde edilen pembe renkli kuvertür. Hafif meyvemsi lezzet profiliyle butik çikolata üretiminde tercih edilir.',
    cocoaContent: '%47',
    weight: ['2.5kg', '5kg'],
    usageArea: 'Butik Üretim, Kaplama, Dekorasyon',
    highlights: ['Doğal Pembe Renk', 'Boyasız', 'Meyvemsi Profil'],
    image: '/images/kuvertür/ruby_kuvertur.png',
    featured: true,
    seoDescription: 'Ruby kuvertür, doğal pembe renkli çikolata',
  },
  {
    id: 'kuv-005',
    name: 'Bitter Kuvertür %85',
    slug: 'bitter-kuvertur-85',
    category: 'kuvertur',
    subcategory: 'Ekstra Bitter',
    badge: 'PROFESSIONAL',
    shortDescription: '%85 kakao içerikli ekstra bitter kuvertür',
    detailedDescription:
      'Minimum şeker içeriğiyle yoğun kakao aroması sunan ekstra bitter kuvertür. Güçlü lezzet profili gerektiren ürünlerde tercih edilir.',
    cocoaContent: '%85',
    weight: ['2.5kg', '5kg', '25kg'],
    usageArea: 'Tablet, Şeker İşleri, İçecek',
    highlights: ['%85 Kakao', 'Minimum Şeker', 'Yoğun Aroma'],
    image: '/images/products/kuvertur-bitter-85.jpg',
    featured: false,
    seoDescription: '%85 ekstra bitter kuvertür, profesyonel çikolata',
  },
  {
    id: 'kuv-006',
    name: 'Karamelize Beyaz Kuvertür',
    slug: 'karamelize-beyaz-kuvertur',
    category: 'kuvertur',
    subcategory: 'Karamelize',
    badge: 'GOLD SERIES',
    shortDescription: 'Karamelize edilmiş beyaz kuvertür',
    detailedDescription:
      'Beyaz kuvertürün yavaş pişirme yöntemiyle karamelize edilmesiyle elde edilen, toffee ve karamel aromalı kuvertür çeşidi.',
    cocoaContent: '%36',
    weight: ['2.5kg', '5kg'],
    usageArea: 'Pralin, Tart, Özel Üretim',
    highlights: ['Karamel Aroması', 'Toffee Notası', 'Özel Üretim'],
    image: '/images/products/kuvertur-karamelize-beyaz.jpg',
    featured: false,
    seoDescription: 'Karamelize beyaz kuvertür, toffee aromalı',
  },
];

// ═══════════════════════════════════════════════════════════════════
// SÜRÜLEBİLİR (4 products)
// ═══════════════════════════════════════════════════════════════════

export const DOLGU_GANAJ_PRODUCTS: Product[] = [
  {
    id: 'sur-001',
    name: 'Fındık Kreması',
    slug: 'findik-kremasi',
    category: 'dolgu-ganaj',
    subcategory: 'Fındık Kreması',
    badge: 'HANDMADE',
    shortDescription: 'Kavanozda sürülebilir doğal fındık kreması',
    detailedDescription:
      'Kavrulmuş iç fındıktan üretilen, pürüzsüz yapısıyla ekmek, krep ve tatlılara kolayca sürülebilen doğal fındık kreması.',
    weight: ['250g', '500g', '1kg'],
    usageArea: 'Ekmek Üzeri, Krep, Waffle, Tatlı Sosları',
    highlights: ['Doğal Fındık', 'Pürüzsüz Yapı', 'Kavanozda Sunum'],
    image: '/images/sürülebilir çikolatalar/fındıkkremasıkavanoz.jpg',
    featured: true,
    seoDescription: 'Sürülebilir fındık kreması, doğal ve pürüzsüz',
  },
  {
    id: 'sur-002',
    name: 'Sütlü Fındık Kreması',
    slug: 'sutlu-findik-kremasi',
    category: 'dolgu-ganaj',
    subcategory: 'Çikolata Kreması',
    badge: 'HANDMADE',
    shortDescription: 'Sütlü çikolata ve fındık karışımlı sürülebilir krema',
    detailedDescription:
      'Sütlü çikolata ve kavrulmuş fındığın uyumundan oluşan, kremsi ve lezzetli sürülebilir çikolata kreması. Her öğünü özel kılar.',
    weight: ['250g', '500g', '1kg'],
    usageArea: 'Ekmek Üzeri, Waffle, Krep, Pasta',
    highlights: ['Sütlü Çikolata', 'Fındık Aroması', 'Kremsi Doku'],
    image: '/images/sürülebilir çikolatalar/sütlüdınfıkkreması.jpg',
    featured: true,
    seoDescription: 'Sütlü fındık kreması, sürülebilir çikolata',
  },
  {
    id: 'sur-003',
    name: 'Pralin',
    slug: 'surülebilir-pralin',
    category: 'dolgu-ganaj',
    subcategory: 'Pralin',
    badge: 'HANDMADE',
    shortDescription: 'Yoğun aromalı sürülebilir çikolata pralin',
    detailedDescription:
      'Kavrulmuş fındık ve şekerin çikolatayla harmanlandığı, zengin aromalı ve kolay sürülebilir el yapımı pralin karışımı.',
    weight: ['250g', '500g', '1kg'],
    usageArea: 'Ekmek Üzeri, Tatlı Dolgu, Pasta',
    highlights: ['Yoğun Aroma', 'El Yapımı', 'Çok Amaçlı'],
    image: '/images/sürülebilir çikolatalar/pralin.jpg',
    featured: true,
    seoDescription: 'Pralin, sürülebilir çikolata karışımı',
  },
  {
    id: 'sur-004',
    name: 'Fildişi Pralin',
    slug: 'fildisi-pralin',
    category: 'dolgu-ganaj',
    subcategory: 'Pralin',
    badge: 'GOLD SERIES',
    shortDescription: 'Beyaz çikolata bazlı narin fildişi pralin',
    detailedDescription:
      'Beyaz çikolata ve fındığın uyumundan oluşan, açık rengi ve narin aromasıyla öne çıkan premium sürülebilir pralin.',
    weight: ['250g', '500g', '1kg'],
    usageArea: 'Tatlı Dolgu, Ekmek Üzeri, Özel Sunum',
    highlights: ['Beyaz Çikolata', 'Fındık Aroması', 'Premium Kalite'],
    image: '/images/sürülebilir çikolatalar/fildisipralin.jpg',
    featured: true,
    seoDescription: 'Fildişi pralin, beyaz çikolata ve fındık',
  },
];

// ═══════════════════════════════════════════════════════════════════
// SOSLAR (dondurma sosu + waffle sosu çeşitleri)
// ═══════════════════════════════════════════════════════════════════

export const SOS_PRODUCTS: Product[] = [
  {
    id: 'sos-101',
    name: 'Çikolatalı Dondurma Sosu',
    slug: 'cikolatali-dondurma-sosu',
    category: 'sos',
    subcategory: 'Dondurma Sosu',
    badge: 'PROFESSIONAL',
    shortDescription: 'Dondurma servisi için akıcı çikolatalı sos',
    detailedDescription:
      'Yoğun çikolata aromasıyla hazırlanmış, dondurma sunumlarında akıcı ve parlak görünüm sağlayan profesyonel çikolata sosu.',
    weight: ['1kg', '3kg', '5kg'],
    usageArea: 'Dondurma Servisi, Waffle, Krep',
    highlights: ['Akıcı Yapı', 'Çikolata Aroması', 'Kolay Dozaj'],
    image: '/images/soslar/çikolatadondurma.png',
    featured: true,
    seoDescription: 'Çikolatalı dondurma sosu, profesyonel servis',
  },
  {
    id: 'sos-102',
    name: 'Çilekli Dondurma Sosu',
    slug: 'cilekli-dondurma-sosu',
    category: 'sos',
    subcategory: 'Dondurma Sosu',
    badge: 'PROFESSIONAL',
    shortDescription: 'Dondurma servisi için taze çilekli sos',
    detailedDescription:
      'Çilek püresi bazlı, canlı rengi ve doğal meyvemsi aromasıyla dondurma sunumlarını taçlandıran profesyonel çilek sosu.',
    weight: ['1kg', '3kg', '5kg'],
    usageArea: 'Dondurma Servisi, Waffle, Krep',
    highlights: ['Doğal Çilek', 'Canlı Renk', 'Meyvemsi Aroma'],
    image: '/images/soslar/çilekdondurma.png',
    featured: true,
    seoDescription: 'Çilekli dondurma sosu, doğal meyve',
  },
  {
    id: 'sos-103',
    name: 'Karamelli Dondurma Sosu',
    slug: 'karamelli-dondurma-sosu',
    category: 'sos',
    subcategory: 'Dondurma Sosu',
    badge: 'PROFESSIONAL',
    shortDescription: 'Dondurma servisi için tereyağlı karamel sos',
    detailedDescription:
      'Tereyağı ve şeker bazlı, sıcak-soğuk servise uygun, zengin karamel aromasıyla dondurma sunumlarını tamamlayan profesyonel karamel sosu.',
    weight: ['1kg', '3kg', '5kg'],
    usageArea: 'Dondurma Servisi, Waffle, Tatlı Üzeri',
    highlights: ['Karamel Aroması', 'Sıcak-Soğuk Servis', 'Tereyağlı'],
    image: '/images/soslar/karameldondurma.png',
    featured: true,
    seoDescription: 'Karamelli dondurma sosu, tereyağlı karamel',
  },
  {
    id: 'sos-104',
    name: 'Vişneli Dondurma Sosu',
    slug: 'visneli-dondurma-sosu',
    category: 'sos',
    subcategory: 'Dondurma Sosu',
    badge: 'PROFESSIONAL',
    shortDescription: 'Dondurma servisi için ekşi-tatlı vişneli sos',
    detailedDescription:
      'Vişne püresi bazlı, ekşi-tatlı dengesiyle dondurma sunumlarına özgün bir karakter katan profesyonel vişne sosu.',
    weight: ['1kg', '3kg', '5kg'],
    usageArea: 'Dondurma Servisi, Waffle, Pasta Üzeri',
    highlights: ['Vişne Aroması', 'Ekşi-Tatlı Denge', 'Doğal Renk'],
    image: '/images/soslar/vişnedondurma.png',
    featured: false,
    seoDescription: 'Vişneli dondurma sosu, ekşi-tatlı',
  },
  {
    id: 'sos-201',
    name: 'Çikolatalı Waffle Sosu',
    slug: 'cikolatali-waffle-sosu',
    category: 'sos',
    subcategory: 'Waffle Sosu',
    badge: 'PROFESSIONAL',
    shortDescription: 'Waffle servisi için akıcı çikolatalı sos',
    detailedDescription:
      'Yoğun çikolata aromasıyla hazırlanmış, waffle sunumlarında sıcak servise uygun, parlak ve akıcı yapıda profesyonel çikolata sosu.',
    weight: ['1kg', '3kg', '5kg'],
    usageArea: 'Waffle Servisi, Dondurma, Krep',
    highlights: ['Akıcı Yapı', 'Sıcak Servise Uygun', 'Parlak Görünüm'],
    image: '/images/soslar/çikolatalı.pngwaffele.png',
    featured: true,
    seoDescription: 'Çikolatalı waffle sosu, sıcak servis',
  },
  {
    id: 'sos-202',
    name: 'Çilekli Waffle Sosu',
    slug: 'cilekli-waffle-sosu',
    category: 'sos',
    subcategory: 'Waffle Sosu',
    badge: 'PROFESSIONAL',
    shortDescription: 'Waffle servisi için taze çilekli sos',
    detailedDescription:
      'Çilek püresi bazlı, ferah meyvemsi aroması ve canlı rengiyle waffle sunumlarını renkli kılan profesyonel çilek sosu.',
    weight: ['1kg', '3kg', '5kg'],
    usageArea: 'Waffle Servisi, Dondurma, Krep',
    highlights: ['Doğal Çilek', 'Ferah Aroma', 'Canlı Renk'],
    image: '/images/soslar/çilekwaffle.png',
    featured: true,
    seoDescription: 'Çilekli waffle sosu, doğal meyve',
  },
  {
    id: 'sos-203',
    name: 'Karamelli Waffle Sosu',
    slug: 'karamelli-waffle-sosu',
    category: 'sos',
    subcategory: 'Waffle Sosu',
    badge: 'PROFESSIONAL',
    shortDescription: 'Waffle servisi için tereyağlı karamel sos',
    detailedDescription:
      'Tereyağı ve şeker bazlı, sıcak servise uygun, zengin karamel aromasıyla waffle sunumlarını tamamlayan profesyonel karamel sosu.',
    weight: ['1kg', '3kg', '5kg'],
    usageArea: 'Waffle Servisi, Dondurma, Tatlı Üzeri',
    highlights: ['Karamel Aroması', 'Sıcak Servise Uygun', 'Tereyağlı'],
    image: '/images/soslar/karamelwaffle.png',
    featured: true,
    seoDescription: 'Karamelli waffle sosu, tereyağlı karamel',
  },
  {
    id: 'sos-204',
    name: 'Fıstık Ezmeli Waffle Sosu',
    slug: 'fistik-ezmeli-waffle-sosu',
    category: 'sos',
    subcategory: 'Waffle Sosu',
    badge: 'PROFESSIONAL',
    shortDescription: 'Waffle servisi için yoğun fıstık ezmeli sos',
    detailedDescription:
      'Kavrulmuş fıstığın yoğun aromasıyla hazırlanmış, waffle sunumlarına farklı bir lezzet boyutu katan profesyonel fıstık ezmeli sos.',
    weight: ['1kg', '3kg', '5kg'],
    usageArea: 'Waffle Servisi, Dondurma, Tatlı Üzeri',
    highlights: ['Fıstık Aroması', 'Yoğun Tat', 'Kremsi Yapı'],
    image: '/images/soslar/fıstıkezmeliwaffle.png',
    featured: false,
    seoDescription: 'Fıstık ezmeli waffle sosu, yoğun aroma',
  },
];

// ═══════════════════════════════════════════════════════════════════
// DAMLA ÇİKOLATALAR
// ═════
export const DAMLA_CIKOLATA_PRODUCTS: Product[] = [
  {
    id: 'dcl-001',
    name: 'Bitter Damla Çikolata %70',
    slug: 'bitter-damla-cikolata-70', 
    category: 'damla-cikolata',
    subcategory: 'Bitter',
    badge: 'PROFESSIONAL',
    shortDescription: '%70 kakao içerikli bitter damla çikolata',
    detailedDescription:
      'Yüksek kakao içeriğiyle yoğun aroma sunan, profesyonel kullanıma uygun bitter damla çikolata. Kek, kurabiye ve tatlılarda ideal.',
    cocoaContent: '%70',
    weight: ['500g', '1kg', '5kg'],
    usageArea: 'Kek, Kurabiye, Tatlı Üzeri',
    highlights: ['%70 Kakao', 'Yoğun Aroma', 'Profesyonel Kullanım'],
    image: '/images/damla çikolata/bitterdamla.png',
    featured: true,
    seoDescription: 'Bitter damla çikolata %70, yoğun aroma',
  },
  {
    id: 'dcl-002',
    name: 'Sütlü Damla Çikolata %38',
    slug: 'sutlu-damla-cikolata-38',
    category: 'damla-cikolata',
    subcategory: 'Sütlü',
    badge: 'PROFESSIONAL',
    shortDescription: '%38 kakao içerikli sütlü damla çikolata',
    detailedDescription:
      'Kakao ve süt oranının dengeli olduğu, kremsi yapıya sahip profesyonel sütlü damla çikolata. Kek ve kurabiye tariflerinde tercih edilir.',
    cocoaContent: '%38',
    weight: ['500g', '1kg', '5kg'],
    usageArea: 'Kek, Kurabiye, Tatlı Üzeri',      
    highlights: ['%38 Kakao', 'Kremsi Yapı', 'Profesyonel Kullanım'],
    image: '/images/damla çikolata/sütlüdamla.png',
    featured: true,
    seoDescription: 'Sütlü damla çikolata %38, kremsi yapı',
  },
  {
    id: 'dcl-003',
    name: 'Fildişi Damla Çikolata %35',
    slug: 'fildisi-damla-cikolata-35',
    category: 'damla-cikolata',
    subcategory: 'Fildişi',
    badge: 'PROFESSIONAL',
    shortDescription: '%35 kakao yağı içerikli fildişi damla çikolata',
    detailedDescription:
      'Saf kakao yağı bazlı, kremsi ve vanilya aromalı profesyonel fildişi damla çikolata. Kek ve kurabiye tariflerinde yumuşak renk ve lezzet için ideal.',
    cocoaContent: '%35 Kakao Yağı',
    weight: ['500g', '1kg', '5kg'],
    usageArea: 'Kek, Kurabiye, Tatlı Üzeri',
    highlights: ['%35 Kakao Yağı', 'Kremsi Renk', 'Profesyonel Kullanım'],
    image: '/images/damla çikolata/fildişi.png',
    featured: true,
    seoDescription: 'Fildişi damla çikolata %35 kakao yağı',
  },
  {
    id: 'dcl-005',
    name: 'Bitter Mini Damla Çikolata',
    slug: 'bitter-mini-damla-cikolata',
    category: 'damla-cikolata',
    subcategory: 'Bitter',
    badge: 'PROFESSIONAL',
    shortDescription: 'Küçük boyutlu bitter damla çikolata',
    detailedDescription:
      'Yoğun bitter aromasını küçük formatta sunan, kek ve kurabiye dolgularında eşit dağılım sağlayan profesyonel mini bitter damla çikolata.',
    cocoaContent: '%70',
    weight: ['500g', '1kg', '5kg'],
    usageArea: 'Kek, Kurabiye, Muffin, Tatlı Dolgu',
    highlights: ['Mini Format', '%70 Kakao', 'Eşit Dağılım'],
    image: '/images/damla çikolata/bitterminidamla.png',
    featured: true,
    seoDescription: 'Bitter mini damla çikolata, küçük boyutlu profesyonel',
  },
  {
    id: 'dcl-006',
    name: 'Sütlü Mini Damla Çikolata',
    slug: 'sutlu-mini-damla-cikolata',
    category: 'damla-cikolata',
    subcategory: 'Sütlü',
    badge: 'PROFESSIONAL',
    shortDescription: 'Küçük boyutlu kremsi sütlü damla çikolata',
    detailedDescription:
      'Kremsi sütlü çikolatanın mini formatta sunumu. Kek ve kurabiye tariflerinde hassas gramaj ve homojen dağılım için idealdir.',
    cocoaContent: '%38',
    weight: ['500g', '1kg', '5kg'],
    usageArea: 'Kek, Kurabiye, Muffin, Tatlı Dolgu',
    highlights: ['Mini Format', 'Kremsi Yapı', 'Homojen Dağılım'],
    image: '/images/damla çikolata/sütlüminidamla.png',
    featured: true,
    seoDescription: 'Sütlü mini damla çikolata, kremsi mini format',
  },
  {
    id: 'dcl-007',
    name: 'Berry Damla Çikolata',
    slug: 'berry-damla-cikolata',
    category: 'damla-cikolata',
    subcategory: 'Meyveli',
    badge: 'HANDMADE',
    shortDescription: 'Berry aromalı sürpriz damla çikolata',
    detailedDescription:
      'Karma berry meyvelerinin yoğun aromasıyla hazırlanmış, tatlı tariflere meyvemsi bir dokunuş katan özel damla çikolata.',
    weight: ['250g', '500g', '1kg'],
    usageArea: 'Kek, Kurabiye, Tatlı Üzeri, Özel Sunum',
    highlights: ['Berry Aroması', 'Meyvemsi Tat', 'Özel Formül'],
    image: '/images/damla çikolata/berrydraje.png',
    featured: true,
    seoDescription: 'Berry damla çikolata, meyveli aromalı',
  },
  {
    id: 'dcl-008',
    name: 'Çilek Damla Çikolata',
    slug: 'cilek-damla-cikolata',
    category: 'damla-cikolata',
    subcategory: 'Meyveli',
    badge: 'HANDMADE',
    shortDescription: 'Çilek aromalı tatlı damla çikolata',
    detailedDescription:
      'Taze çilek aromasıyla hazırlanmış, tatlı ve kek tariflerine ferah meyvemsi lezzet katan el yapımı damla çikolata.',
    weight: ['250g', '500g', '1kg'],
    usageArea: 'Kek, Kurabiye, Tatlı Üzeri, Özel Sunum',
    highlights: ['Çilek Aroması', 'Ferah Tat', 'El Yapımı'],
    image: '/images/damla çikolata/çilekdraje.png',
    featured: true,
    seoDescription: 'Çilek damla çikolata, çilek aromalı tatlı',
  },
  {
    id: 'dcl-009',
    name: 'Mango Damla Çikolata',
    slug: 'mango-damla-cikolata',
    category: 'damla-cikolata',
    subcategory: 'Meyveli',
    badge: 'HANDMADE',
    shortDescription: 'Egzotik mango aromalı damla çikolata',
    detailedDescription:
      'Tropikal mango aromasıyla hazırlanmış, kek ve tatlı tariflerine egzotik bir lezzet katan özel damla çikolata.',
    weight: ['250g', '500g', '1kg'],
    usageArea: 'Kek, Kurabiye, Tatlı Üzeri',
    highlights: ['Mango Aroması', 'Egzotik Tat', 'Tropikal'],
    image: '/images/damla çikolata/mango.png',
    featured: true,
    seoDescription: 'Mango damla çikolata, egzotik mango aromalı',
  },
  {
    id: 'dcl-010',
    name: 'Portakal Damla Çikolata',
    slug: 'portakal-damla-cikolata',
    category: 'damla-cikolata',
    subcategory: 'Meyveli',
    badge: 'HANDMADE',
    shortDescription: 'Ferah portakal aromalı damla çikolata',
    detailedDescription:
      'Taze portakal kabuğu aromasıyla hazırlanmış, tatlı tariflere ferahlatıcı narenciye lezzeti katan özel damla çikolata.',
    weight: ['250g', '500g', '1kg'],
    usageArea: 'Kek, Kurabiye, Tatlı Üzeri',
    highlights: ['Portakal Aroması', 'Ferah Tat', 'Narenciye'],
    image: '/images/damla çikolata/portakal.png',
    featured: true,
    seoDescription: 'Portakal damla çikolata, narenciye aromalı',
  },
  {
    id: 'dcl-011',
    name: 'İtalyan Karameli Damla Çikolata',
    slug: 'italyan-karameli-damla-cikolata',
    category: 'damla-cikolata',
    subcategory: 'Karamelli',
    badge: 'GOLD SERIES',
    shortDescription: 'İtalyan usulü zengin karamel aromalı damla çikolata',
    detailedDescription:
      'İtalyan tatlı geleneğinden ilham alınan, derin ve kremsi karamel aromasıyla tatlı tariflere sofistike bir lezzet katan özel damla çikolata.',
    weight: ['250g', '500g', '1kg'],
    usageArea: 'Kek, Kurabiye, Pasta, Özel Sunum',
    highlights: ['İtalyan Karamel', 'Derin Aroma', 'Kremsi Tat'],
    image: '/images/damla çikolata/italyan karameli.png',
    featured: true,
    seoDescription: 'İtalyan karameli damla çikolata, sofistike aroma',
  },
  {
    id: 'dcl-012',
    name: 'Mor Meyve Damla Çikolata',
    slug: 'mor-meyve-damla-cikolata',
    category: 'damla-cikolata',
    subcategory: 'Meyveli',
    badge: 'HANDMADE',
    shortDescription: 'Karışık mor meyve aromalı damla çikolata',
    detailedDescription:
      'Böğürtlen, yaban mersini ve vişne aromasının buluştuğu, tatlı tariflere yoğun meyvemsi renk ve tat katan özel damla çikolata.',
    weight: ['250g', '500g', '1kg'],
    usageArea: 'Kek, Kurabiye, Tatlı Üzeri',
    highlights: ['Mor Meyve Karışımı', 'Yoğun Renk', 'Meyvemsi Tat'],
    image: '/images/damla çikolata/mor meyveler.png',
    featured: true,
    seoDescription: 'Mor meyve damla çikolata, karışık berry',
  },
  {
    id: 'dcl-013',
    name: 'Tiramisu Damla Çikolata',
    slug: 'tiramisu-damla-cikolata',
    category: 'damla-cikolata',
    subcategory: 'Özel Tat',
    badge: 'GOLD SERIES',
    shortDescription: 'Tiramisu aromalı özel damla çikolata',
    detailedDescription:
      'Mascarpone ve kahve aromasının uyumundan oluşan, İtalyan tiramisu tatlısından ilham alan sofistike damla çikolata.',
    weight: ['250g', '500g', '1kg'],
    usageArea: 'Kek, Kurabiye, Pasta, Özel Sunum',
    highlights: ['Tiramisu Aroması', 'Mascarpone Notası', 'Sofistike Tat'],
    image: '/images/damla çikolata/tiramisu.png',
    featured: true,
    seoDescription: 'Tiramisu damla çikolata, mascarpone ve kahve',
  },
  {
    id: 'dcl-014',
    name: 'Karamel Damla Çikolata',
    slug: 'karamel-damla-cikolata',
    category: 'damla-cikolata',
    subcategory: 'Karamelli',
    badge: 'HANDMADE',
    shortDescription: 'Klasik karamel aromalı damla çikolata',
    detailedDescription:
      'Toffee ve tereyağlı karamel aromasıyla hazırlanmış, kek ve kurabiye tariflerine tatlı ve kremsi bir derinlik katan damla çikolata.',
    weight: ['250g', '500g', '1kg'],
    usageArea: 'Kek, Kurabiye, Tatlı Üzeri',
    highlights: ['Karamel Aroması', 'Toffee Notası', 'Kremsi Tat'],
    image: '/images/damla çikolata/karamel.png',
    featured: true,
    seoDescription: 'Karamel damla çikolata, toffee aromalı',
  },
  {
    id: 'dcl-015',
    name: 'Limon Damla Çikolata',
    slug: 'limon-damla-cikolata',
    category: 'damla-cikolata',
    subcategory: 'Meyveli',
    badge: 'HANDMADE',
    shortDescription: 'Ekşi-tatlı limon aromalı damla çikolata',
    detailedDescription:
      'Taze limon kabuğu aromasıyla hazırlanmış, tatlı tariflere ferahlatıcı ve ekşi-tatlı bir karakter katan özel damla çikolata.',
    weight: ['250g', '500g', '1kg'],
    usageArea: 'Kek, Kurabiye, Tatlı Üzeri',
    highlights: ['Limon Aroması', 'Ekşi-Tatlı Denge', 'Ferahlatıcı'],
    image: '/images/damla çikolata/limon.png',
    featured: false,
    seoDescription: 'Limon damla çikolata, narenciye ekşi-tatlı',
  },
  {
    id: 'dcl-016',
    name: 'Muz Damla Çikolata',
    slug: 'muz-damla-cikolata',
    category: 'damla-cikolata',
    subcategory: 'Meyveli',
    badge: 'HANDMADE',
    shortDescription: 'Kremsi muz aromalı damla çikolata',
    detailedDescription:
      'Olgun muz aromasıyla hazırlanmış, tatlı tariflere tropikal ve kremsi bir lezzet boyutu katan özel damla çikolata.',
    weight: ['250g', '500g', '1kg'],
    usageArea: 'Kek, Kurabiye, Tatlı Üzeri',
    highlights: ['Muz Aroması', 'Kremsi Tat', 'Tropikal'],
    image: '/images/damla çikolata/muz.png',
    featured: false,
    seoDescription: 'Muz damla çikolata, kremsi muz aromalı',
  },
  {
    id: 'dcl-017',
    name: 'Antep Fıstığı Damla Çikolata',
    slug: 'antep-fistigi-damla-cikolata',
    category: 'damla-cikolata',
    subcategory: 'Kuruyemiş',
    badge: 'GOLD SERIES',
    shortDescription: 'Yoğun antep fıstığı aromalı damla çikolata',
    detailedDescription:
      'Kavrulmuş antep fıstığının yoğun ve özgün aromasıyla hazırlanmış, kek ve pasta tariflerine premium bir lezzet katan özel damla çikolata.',
    weight: ['250g', '500g', '1kg'],
    usageArea: 'Kek, Kurabiye, Pasta, Özel Sunum',
    highlights: ['Antep Fıstığı Aroması', 'Yoğun Tat', 'Premium Kalite'],
    image: '/images/damla çikolata/antep fıstığı.png',
    featured: true,
    seoDescription: 'Antep fıstığı damla çikolata, premium aroma',
  },
];


// ═══════════════════════════════════════════════════════════════════
// DRAJELER (19 products)
// ═══════════════════════════════════════════════════════════════════

export const DRAJELER_PRODUCTS: Product[] = [
  {
    id: 'drj-001',
    name: 'Antepfıstığı Draje',
    slug: 'antepfistigi-draje',
    category: 'drajeler',
    subcategory: 'Kuruyemiş',
    badge: 'HANDMADE',
    shortDescription: 'Antepfıstığı çekirdeğinin çikolata ile kaplanmış hali',
    detailedDescription:
      'Kaliteli antepfıstığı çekirdeğinin ince çikolata tabakasıyla kaplanmış, lezzetli ve çıtır drajeler. Tatlı seçenekleri ve hediye paketlerine ideal.',
    weight: ['500g', '1kg', '2kg'],
    usageArea: 'Hediye Paketi, Tatlı Seçenekleri, Masa Sunumu',
    highlights: ['Antepfıstığı İçi', 'Çikolata Kaplaması', 'Çıtır Tekstür'],
    image: '/images/products/draje-antepfistigi.jpg',
    featured: true,
    seoDescription: 'Antepfıstığı draje, çikolata kaplı',
  },
  {
    id: 'drj-002',
    name: 'Badem Draje',
    slug: 'badem-draje',
    category: 'drajeler',
    subcategory: 'Kuruyemiş',
    badge: 'HANDMADE',
    shortDescription: 'Kavrulmuş badem çekirdeğinin çikolata kaplaması',
    detailedDescription:
      'Taze kavrulmuş badem çekirdeğinin lezzetli çikolata tabakasıyla kaplanmış, yumuşak dış ve çıtır iç yapıya sahip drajeler.',
    weight: ['500g', '1kg', '2kg'],
    usageArea: 'Hediye Paketi, Tatlı Seçenekleri, Parti',
    highlights: ['Kavrulmuş Badem', 'İnce Kaplama', 'Yumuşak Dış'],
    image: '/images/drajeler/bademdraje.png',
    featured: true,
    seoDescription: 'Badem draje, çikolata kaplı badem',
  },
  {
    id: 'drj-003',
    name: 'Badem Şekeri',
    slug: 'badem-sekeri',
    category: 'drajeler',
    subcategory: 'Şeker Coated',
    badge: 'HANDMADE',
    shortDescription: 'Şeker kaplaması yapılmış kavrulmuş badem',
    detailedDescription:
      'Kavrulmuş bademin kırılgan şeker kaplamasıyla kaplı, tatlı ve çıtır yapıda badem şekeri. Nostaljik tatlı tercihi.',
    weight: ['500g', '1kg'],
    usageArea: 'Tatlı Seçenekleri, Nostalji Ürünü, Hediye',
    highlights: ['Kavrulmuş Badem', 'Şeker Kaplama', 'Çıtır Yapı'],
    image: '/images/drajeler/bademşekeri.png',
    featured: true,
    seoDescription: 'Badem şekeri, şeker kaplı badem',
  },
  {
    id: 'drj-004',
    name: 'Bonibon',
    slug: 'bonibon',
    category: 'drajeler',
    subcategory: 'Bonbon',
    badge: 'HANDMADE',
    shortDescription: 'Renkli ve lezzetli çikolata bonbonları',
    detailedDescription:
      'Çeşitli tatlarıyla hazırlanan, renkli çikolata kaplamasıyla sunulan bonbon drajeler. Her bir tadında farklı bir lezzet deneyimi.',
    weight: ['500g', '1kg'],
    usageArea: 'Hediye Paketi, Tatlı Seçenekleri, Özel Günler',
    highlights: ['Çok Tatl', 'Renkli Kaplama', 'Gourmet Deneyim'],
    image: '/images/drajeler/bonibondraje.png',
    featured: true,
    seoDescription: 'Bonibon, renkli çikolata bonbonları',
  },
  {
    id: 'drj-005',
    name: 'Bronz Kahve',
    slug: 'bronz-kahve',
    category: 'drajeler',
    subcategory: 'Kahve Aromalı',
    badge: 'HANDMADE',
    shortDescription: 'Kahve aromalı çikolata drajesi',
    detailedDescription:
      'Yoğun kahve aromasıyla hazırlanan, kahve severler için tasarlanmış bronze renkli çikolata kaplamalı draje.',
    weight: ['500g', '1kg'],
    usageArea: 'Kahve Severleri, Tatlı Seçenekleri, Hediye',
    highlights: ['Kahve Aroması', 'Bronze Renk', 'Yoğun Tat'],
    image: '/images/drajeler/bronzdraje.png',
    featured: true,
    seoDescription: 'Bronz kahve draje, kahve aromalı',
  },
  {
    id: 'drj-006',
    name: 'Çakıltaşı',
    slug: 'cakiltasi',
    category: 'drajeler',
    subcategory: 'Klasik',
    badge: 'HANDMADE',
    shortDescription: 'Geleneksel çakıltaşı şekli draje',
    detailedDescription:
      'Çıtır ve hafif kavrulmuş çekirdeğin şeker tarafından çevrili, geleneksel çakıltaşı şeklinde draje. Klasik tatlı tercihlerinin favorisi.',
    weight: ['500g', '1kg'],
    usageArea: 'Tatlı Seçenekleri, Geleneksel, Masa Sunumu',
    highlights: ['Geleneksel Şekil', 'Şeker Kaplaması', 'Çıtır Yapı'],
    image: '/images/drajeler/çakıltaşı.png',
    featured: true,
    seoDescription: 'Çakıltaşı draje, geleneksel çikolata',
  },
  {
    id: 'drj-007',
    name: 'Fındık Draje',
    slug: 'findik-draje',
    category: 'drajeler',
    subcategory: 'Kuruyemiş',
    badge: 'HANDMADE',
    shortDescription: 'İç fındığın çikolata kaplaması',
    detailedDescription:
      'Seçilmiş iç fındığının ince çikolata tabakasıyla kaplanmış, fındık severlerin favori seçeneği olan draje.',
    weight: ['500g', '1kg', '2kg'],
    usageArea: 'Hediye Paketi, Tatlı Seçenekleri, Premium Sunumu',
    highlights: ['İç Fındık', 'Çikolata Kaplaması', 'Premium Kalite'],
    image: '/images/drajeler/sütlüfındıkdraje.png',
    featured: true,
    seoDescription: 'Fındık draje, çikolata kaplı fındık',
  },
  {
    id: 'drj-007b',
    name: 'Bitter Fındık Draje',
    slug: 'bitter-findik-draje',
    category: 'drajeler',
    subcategory: 'Kuruyemiş',
    badge: 'HANDMADE',
    shortDescription: 'İç fındığın bitter çikolata kaplaması',
    detailedDescription:
      'Seçilmiş iç fındığının yoğun bitter çikolata tabakasıyla kaplanmış, çikolata severlerin favorisi olan draje.',
    weight: ['500g', '1kg', '2kg'],
    usageArea: 'Hediye Paketi, Tatlı Seçenekleri, Premium Sunumu',
    highlights: ['İç Fındık', 'Bitter Çikolata', 'Yoğun Tat'],
    image: '/images/drajeler/bitterfındıkdraje.png',
    featured: true,
    seoDescription: 'Bitter fındık draje, bitter çikolata kaplı fındık',
  },
  {
    id: 'drj-008',
    name: 'Kahve Mix',
    slug: 'kahve-mix',
    category: 'drajeler',
    subcategory: 'Kahve Aromalı',
    badge: 'HANDMADE',
    shortDescription: 'Çeşitli kahve aromalı drajeler karışımı',
    detailedDescription:
      'Kahve aromasının farklı yoğunluklarda sunulduğu, çeşitli çikolata kaplamalı kahve draje mix. Her birinde farklı bir kahve deneyimi.',
    weight: ['500g', '1kg'],
    usageArea: 'Kahve Seçenekleri, Hediye Paketi, Profesyonel Sunumu',
    highlights: ['Kahve Aroması', 'Çeşitli Çikolata', 'Mix Ürün'],
    image: '/images/drajeler/kahve_cekirdekli_draje.png',
    featured: false,
    seoDescription: 'Kahve mix draje, karışık kahve aromalı',
  },
  {
    id: 'drj-009',
    name: 'Kalp Draje',
    slug: 'kalp-draje',
    category: 'drajeler',
    subcategory: 'Özel Şekil',
    badge: 'HANDMADE',
    shortDescription: 'Sevgi sembolü kalp şeklinde draje',
    detailedDescription:
      'Romantik kalp şeklinde, çikolata ve renkli kaplama seçenekleriyle sunulan draje. Sevgili hediyesi ve özel günlerin favorisi.',
    weight: ['250g', '500g'],
    usageArea: 'Sevgili Hediyesi, Özel Günler, Romantik Sunumu',
    highlights: ['Kalp Şekli', 'Romantik Tasarım', 'Özel Kaplama'],
    image: '/images/drajeler/kalp_draje.png',
    featured: true,
    seoDescription: 'Kalp draje, romantik şekil',
  },
  {
    id: 'drj-011',
    name: 'Narlı Fındık',
    slug: 'narli-findik',
    category: 'drajeler',
    subcategory: 'Meyveli',
    badge: 'HANDMADE',
    shortDescription: 'Fındık içi, nar aromalı çikolata kaplaması',
    detailedDescription:
      'Fringe nar aromasıyla kaplanmış fındık draje. Meyvemsi lezzet sevenlerin seçim yapabileceği, farklı bir kombinasyon.',
    weight: ['500g', '1kg'],
    usageArea: 'Tatlı Seçenekleri, Meyveli Ürünler, Hediye',
    highlights: ['Fındık İçi', 'Nar Aroması', 'Meyvemsi Tat'],
    image: '/images/drajeler/narlıfındıkdraje.png',
    featured: false,
    seoDescription: 'Narlı fındık draje, nar aromalı',
  },
  {
    id: 'drj-012',
    name: 'Portakal Draje',
    slug: 'portakal-draje',
    category: 'drajeler',
    subcategory: 'Meyveli',
    badge: 'HANDMADE',
    shortDescription: 'Portakal aromalı çikolata kaplı draje',
    detailedDescription:
      'Taze portakal aromasıyla enerji veren çikolata draje. Meyvemsi ve ferahlatıcı lezzetiyle yaz aylarının favorisi.',
    weight: ['500g', '1kg'],
    usageArea: 'Meyveli Seçenekler, Yaz Tatlıları, Hediye',
    highlights: ['Portakal Aroması', 'Ferah Tat', 'Meyveli'],
    image: '/images/drajeler/portakaldraje.png',
    featured: false,
    seoDescription: 'Portakal draje, portakal aromalı',
  },
  {
    id: 'drj-013',
    name: 'Pütürlü Badem',
    slug: 'puturlulu-badem',
    category: 'drajeler',
    subcategory: 'Kuruyemiş',
    badge: 'HANDMADE',
    shortDescription: 'Pürüzlü çikolata kaplamalı badem',
    detailedDescription:
      'Kavrulmuş bademin pürüzlü ve çok katmanlı çikolata kaplamasıyla sunulan, tekstürlü görüntü ve yoğun lezzeti olan draje.',
    weight: ['500g', '1kg'],
    usageArea: 'Hediye Paketi, Tatlı Seçenekleri, Premium Sunumu',
    highlights: ['Pütürlü Kaplama', 'Badem İçi', 'Tekstürlü Görüntü'],
    image: '/images/drajeler/pütürlübadem.png',
    featured: true,
    seoDescription: 'Pütürlü badem draje, pürüzlü kaplama',
  },
  {
    id: 'drj-014',
    name: 'Pütürlü Fındık',
    slug: 'puturlulu-findik',
    category: 'drajeler',
    subcategory: 'Kuruyemiş',
    badge: 'HANDMADE',
    shortDescription: 'Pürüzlü çikolata kaplamalı fındık',
    detailedDescription:
      'Fındığın pürüzlü ve çok katmanlı çikolata kaplamasıyla sunulan, görsel olarak çekici ve lezzetli premium draje.',
    weight: ['500g', '1kg', '2kg'],
    usageArea: 'Hediye Paketi, Premium Sunumu, Özel Sunumu',
    highlights: ['Pütürlü Kaplama', 'Fındık İçi', 'Premium Tasarım'],
    image: '/images/drajeler/pütürlüfındık.png',
    featured: true,
    seoDescription: 'Pütürlü fındık draje, pürüzlü kaplama',
  },
  {
    id: 'drj-015',
    name: 'Rainbow',
    slug: 'rainbow',
    category: 'drajeler',
    subcategory: 'Renkli',
    badge: 'HANDMADE',
    shortDescription: 'Renkli çikolata kaplama yapılmış drajeler',
    detailedDescription:
      'Gökkuşağı renklerinde farklı çikolata kaplamalı drajeler. Çocuklu aileler ve eğlenceli sunumlar için ideal seçim.',
    weight: ['500g', '1kg'],
    usageArea: 'Çocuk Partileri, Renkli Sunumlar, Hediye',
    highlights: ['Renkli Kaplama', 'Gökkuşağı Renkleri', 'Eğlenceli'],
    image: '/images/products/draje-rainbow.jpg',
    featured: false,
    seoDescription: 'Rainbow draje, renkli çikolata drajeler',
  },
  {
    id: 'drj-017',
    name: 'Tramisu Ceviz',
    slug: 'tramisu-ceviz',
    category: 'drajeler',
    subcategory: 'Özel Tat',
    badge: 'GOLD SERIES',
    shortDescription: 'Tramisu aromalı çikolata kaplı ceviz',
    detailedDescription:
      'Tramisu tatlısının aromasıyla hazırlanan ceviz draje. Sofistike tat sevenlerin seçimi olan özel kombinasyon.',
    weight: ['500g', '1kg'],
    usageArea: 'Gourmet Seçenek, Hediye Paketi, Özel Sunumu',
    highlights: ['Tramisu Aroması', 'Ceviz İçi', 'Sofistike Tat'],
    image: '/images/drajeler/cevizdraje.png',
    featured: false,
    seoDescription: 'Tramisu ceviz draje, tramisu aromalı',
  },
  {
    id: 'drj-018',
    name: 'Üzüm Draje',
    slug: 'uzum-draje',
    category: 'drajeler',
    subcategory: 'Meyveli',
    badge: 'HANDMADE',
    shortDescription: 'Kuru üzüm çekirdeğinin çikolata kaplaması',
    detailedDescription:
      'Seçilmiş kuru üzüm çekirdeğinin ince çikolata tabakasıyla kaplanmış, doğal meyvemsi lezzeti olan draje.',
    weight: ['500g', '1kg'],
    usageArea: 'Meyveli Seçenekler, Tatlı Seçenekleri, Hediye',
    highlights: ['Kuru Üzüm', 'Çikolata Kaplaması', 'Meyvemsi'],
    image: '/images/drajeler/üzümdraje.png',
    featured: false,
    seoDescription: 'Üzüm draje, kuru üzüm çikolata',
  },
  {
    id: 'drj-019',
    name: 'Yeşil Pütürlü Badem',
    slug: 'yesil-puturlulu-badem',
    category: 'drajeler',
    subcategory: 'Renkli',
    badge: 'HANDMADE',
    shortDescription: 'Yeşil pürüzlü çikolata kaplı badem',
    detailedDescription:
      'Bademin yeşil renkli pürüzlü çikolata kaplamasıyla sunulan, göz alıcı ve lezzetli premium draje. Bahar koleksiyonu favori.',
    weight: ['500g', '1kg'],
    usageArea: 'Hediye Paketi, Mevsimlik Sunumu, Özel Tasarım',
    highlights: ['Yeşil Renk', 'Pütürlü Kaplama', 'Premium Tasarım'],
    image: '/images/drajeler/yesil_puturlu_badem_draje.png',
    featured: false,
    seoDescription: 'Yeşil pütürlü badem draje, yeşil renkli',
  },
  {
    id: 'drj-020',
    name: 'Sütlü Ceviz Draje',
    slug: 'sutlu-ceviz-draje',
    category: 'drajeler',
    subcategory: 'Kuruyemiş',
    badge: 'HANDMADE',
    shortDescription: 'Sütlü çikolata kaplamalı ceviz draje',
    detailedDescription:
      'Seçilmiş ceviz içinin kremsi sütlü çikolata tabakasıyla kaplanmış, hafif tatlı ve yoğun ceviz aromalı draje.',
    weight: ['500g', '1kg'],
    usageArea: 'Hediye Paketi, Tatlı Seçenekleri, Masa Sunumu',
    highlights: ['Ceviz İçi', 'Sütlü Kaplama', 'Kremsi Tat'],
    image: '/images/drajeler/sutlu_ceviz_draje.png',
    featured: false,
    seoDescription: 'Sütlü ceviz draje, sütlü çikolata kaplı',
  },
];

// ═══════════════════════════════════════════════════════════════════
// SPECIAL PRODUCTS
// ═══════════════════════════════════════════════════════════════════

export const SPECIAL_PRODUCTS: Product[] = [
  {
    id: 'special-001',
    name: 'Special Çikolata',
    slug: 'special-cikolata',
    category: 'special',
    subcategory: 'Special',
    badge: 'GOLD SERIES',
    shortDescription: 'El yapımı özel çikolata koleksiyonu',
    detailedDescription:
      'Altın varak ve kakao tozu ile ustalıkla işlenmiş, her biri kendine özgü form ve aromaya sahip özel el yapımı çikolata koleksiyonu.',
    weight: ['6\'lı', '12\'li', '24\'lü'],
    usageArea: 'Hediye, Özel Gün, Sunum',
    highlights: ['El Yapımı', 'Altın Varak', 'Özel Koleksiyon'],
    image: '/images/special/specialcikolata1.png',
    images: [
      '/images/special/specialcikolata1.png',
      '/images/special/specialcikolata2.png',
      '/images/special/specialcikolata3.png',
      '/images/special/specialcikolata4.jpeg',
    ],
    featured: true,
    seoDescription: 'El yapımı special çikolata koleksiyonu, altın varak',
  },
  {
    id: 'madlen-002',
    name: 'Sütlü Madlen Çikolata',
    slug: 'sutlu-madlen-cikolata',
    category: 'special',
    subcategory: 'Madlen',
    badge: 'PROFESSIONAL',
    shortDescription: '%30 kakao içerikli kremsi sütlü madlen çikolata',
    detailedDescription:
      'Sütlü madlen çikolata, %30 kakao içeriğiyle zenginleştirilmiş, kremsi ve tatlı bir lezzete sahip profesyonel çikolata ürünü.',
    cocoaContent: '%30',
    weight: ['500g', '1kg', '5kg', '25kg'],
    usageArea: 'Pasta, Tatlı, Sunum',
    highlights: ['%30 Kakao', 'Kremsi Yapı', 'Geniş Kullanım'],
    image: '/images/special/sutlu_madlen_1.png',
    featured: true,
    seoDescription: 'Sütlü madlen çikolata, %30 kakao içeriği',
  },
  {
    id: 'madlen-003',
    name: 'Bitter Madlen Çikolata',
    slug: 'bitter-madlen-cikolata',
    category: 'special',
    subcategory: 'Madlen',
    badge: 'PROFESSIONAL',
    shortDescription: '%70 kakao içerikli yoğun bitter madlen çikolata',
    detailedDescription:
      'Bitter madlen çikolata, %70 kakao içeriğiyle yoğun ve derin aromasıyla öne çıkan, profesyonel kullanıma uygun premium çikolata ürünü.',
    cocoaContent: '%70',
    weight: ['500g', '1kg', '5kg', '25kg'],
    usageArea: 'Pasta, Tatlı, Sunum',
    highlights: ['%70 Kakao', 'Yoğun Aroma', 'Premium Kalite'],
    image: '/images/special/bitter_madlen_koyu.png',
    featured: true,
    seoDescription: 'Bitter madlen çikolata, %70 kakao içeriği',
  },
];

// ═══════════════════════════════════════════════════════════════════
// VERMİCELLİ (4 products)
// ═══════════════════════════════════════════════════════════════════

export const VERMICELLI_PRODUCTS: Product[] = [
  {
    id: 'vrm-001',
    name: 'Sütlü Vermicelli',
    slug: 'sutlu-vermicelli',
    category: 'vermicelli',
    subcategory: 'Sütlü',
    badge: 'PROFESSIONAL',
    shortDescription: 'Kremsi sütlü çikolata vermicelli',
    detailedDescription:
      'Kremsi sütlü çikolatadan üretilmiş ince vermicelli. Pasta, dondurma ve tatlı dekorasyonlarında pürüzsüz bir kaplama ve yoğun lezzet sunar.',
    weight: ['500g', '1kg', '5kg'],
    usageArea: 'Pasta Dekor, Dondurma, Tatlı Kaplama',
    highlights: ['Sütlü Çikolata', 'İnce Yapı', 'Kolay Uygulama'],
    image: '/images/vermicelli/sütlüvermicelli.png',
    featured: true,
    seoDescription: 'Sütlü vermicelli, pasta ve tatlı dekorasyonu',
  },
  {
    id: 'vrm-002',
    name: 'Bitter Vermicelli',
    slug: 'bitter-vermicelli',
    category: 'vermicelli',
    subcategory: 'Bitter',
    badge: 'PROFESSIONAL',
    shortDescription: 'Yoğun aromalı bitter çikolata vermicelli',
    detailedDescription:
      'Yüksek kakao içerikli bitter çikolatadan üretilmiş ince vermicelli. Tatlılara derin çikolata aroması ve kontrast renk katar.',
    weight: ['500g', '1kg', '5kg'],
    usageArea: 'Pasta Dekor, Dondurma, Tatlı Kaplama',
    highlights: ['Bitter Çikolata', 'Yoğun Aroma', 'Koyu Renk'],
    image: '/images/vermicelli/bittervermicelli.png',
    featured: true,
    seoDescription: 'Bitter vermicelli, yoğun kakao aromalı',
  },
  {
    id: 'vrm-003',
    name: 'Fildişi Vermicelli',
    slug: 'fildisi-vermicelli',
    category: 'vermicelli',
    subcategory: 'Fildişi',
    badge: 'PROFESSIONAL',
    shortDescription: 'Narin fildişi renkli beyaz çikolata vermicelli',
    detailedDescription:
      'Beyaz çikolata bazlı, vanilya aromalı ve fildişi renkli vermicelli. Açık tonlarda dekorasyon gerektiren tatlılarda idealdir.',
    weight: ['500g', '1kg', '5kg'],
    usageArea: 'Pasta Dekor, Dondurma, Tatlı Kaplama',
    highlights: ['Beyaz Çikolata', 'Vanilya Aroması', 'Fildişi Renk'],
    image: '/images/vermicelli/fildişivermicelli.png',
    featured: true,
    seoDescription: 'Fildişi vermicelli, vanilya aromalı beyaz çikolata',
  },
  {
    id: 'vrm-004',
    name: 'Frambuaz Vermicelli',
    slug: 'frambuaz-vermicelli',
    category: 'vermicelli',
    subcategory: 'Frambuaz',
    badge: 'HANDMADE',
    shortDescription: 'Meyvemsi frambuaz aromalı pembe vermicelli',
    detailedDescription:
      'Frambuaz aromasıyla hazırlanmış, canlı pembe rengi ve meyvemsi lezzetiyle tatlı dekorasyonlarına renk ve ferahlık katan özel vermicelli.',
    weight: ['500g', '1kg'],
    usageArea: 'Pasta Dekor, Dondurma, Özel Sunum',
    highlights: ['Frambuaz Aroması', 'Pembe Renk', 'Meyvemsi Tat'],
    image: '/images/vermicelli/frambuazvermicelli.png',
    featured: true,
    seoDescription: 'Frambuaz vermicelli, pembe meyvemsi dekor',
  },
];

// ═══════════════════════════════════════════════════════════════════
// PARÇA / KIRINTΙ ÇİKOLATA (5 products)
// ═══════════════════════════════════════════════════════════════════

export const PARCA_KIRINTI_PRODUCTS: Product[] = [
  {
    id: 'pkr-001',
    name: 'Sütlü Parça Çikolata',
    slug: 'sutlu-parca-cikolata',
    category: 'parca-kirintı',
    subcategory: 'Parça',
    badge: 'PROFESSIONAL',
    shortDescription: 'Düzensiz kırık sütlü çikolata parçaları',
    detailedDescription:
      'Kremsi sütlü kuvertürden elde edilen, farklı boyutlardaki çikolata parçaları. Pasta, brownie ve tatlı dolgularında eşsiz doku ve lezzet sağlar.',
    weight: ['500g', '1kg', '5kg'],
    usageArea: 'Pasta Dolgu, Brownie, Tatlı Üzeri, Dekor',
    highlights: ['Sütlü Çikolata', 'Düzensiz Parça', 'Kremsi Tat'],
    image: '/images/parça/kırıntı /sütlüparça.png',
    featured: true,
    seoDescription: 'Sütlü parça çikolata, pasta ve brownie',
  },
  {
    id: 'pkr-002',
    name: 'Bitter Parça Çikolata',
    slug: 'bitter-parca-cikolata',
    category: 'parca-kirintı',
    subcategory: 'Parça',
    badge: 'PROFESSIONAL',
    shortDescription: 'Düzensiz kırık bitter çikolata parçaları',
    detailedDescription:
      'Yüksek kakao içerikli bitter kuvertürden elde edilen çikolata parçaları. Yoğun kakao aroması gerektiren tatlı ve pasta tariflerinde tercih edilir.',
    weight: ['500g', '1kg', '5kg'],
    usageArea: 'Pasta Dolgu, Brownie, Tatlı Üzeri, Dekor',
    highlights: ['Bitter Çikolata', 'Düzensiz Parça', 'Yoğun Aroma'],
    image: '/images/parça/kırıntı /bitterparça.png',
    featured: true,
    seoDescription: 'Bitter parça çikolata, yüksek kakao',
  },
  {
    id: 'pkr-003',
    name: 'Sütlü Kırıntı Çikolata',
    slug: 'sutlu-kirinti-cikolata',
    category: 'parca-kirintı',
    subcategory: 'Kırıntı',
    badge: 'PROFESSIONAL',
    shortDescription: 'İnce kırılmış sütlü çikolata kırıntıları',
    detailedDescription:
      'Sütlü kuvertürden elde edilen küçük ve ince çikolata kırıntıları. Dondurma, cheesecake ve tatlı yüzeylerine eşit dağılımlı kaplama için idealdir.',
    weight: ['500g', '1kg', '5kg'],
    usageArea: 'Dondurma, Cheesecake, Tatlı Yüzeyi, Dekor',
    highlights: ['Sütlü Çikolata', 'İnce Kırıntı', 'Homojen Dağılım'],
    image: '/images/parça/kırıntı /sütlükırıntı.png',
    featured: true,
    seoDescription: 'Sütlü kırıntı çikolata, tatlı kaplama',
  },
  {
    id: 'pkr-004',
    name: 'Bitter Kırıntı Çikolata',
    slug: 'bitter-kirinti-cikolata',
    category: 'parca-kirintı',
    subcategory: 'Kırıntı',
    badge: 'PROFESSIONAL',
    shortDescription: 'İnce kırılmış bitter çikolata kırıntıları',
    detailedDescription:
      'Bitter kuvertürden elde edilen küçük çikolata kırıntıları. Yoğun kakao aromasıyla tatlılara derinlik ve çıtır doku katar.',
    weight: ['500g', '1kg', '5kg'],
    usageArea: 'Dondurma, Cheesecake, Tatlı Yüzeyi, Dekor',
    highlights: ['Bitter Çikolata', 'İnce Kırıntı', 'Yoğun Aroma'],
    image: '/images/parça/kırıntı /bitterkırıntı.png',
    featured: true,
    seoDescription: 'Bitter kırıntı çikolata, yoğun kakao',
  },
  {
    id: 'pkr-005',
    name: 'Fildişi Kırıntı Çikolata',
    slug: 'fildisi-kirinti-cikolata',
    category: 'parca-kirintı',
    subcategory: 'Kırıntı',
    badge: 'PROFESSIONAL',
    shortDescription: 'Narin fildişi renkli beyaz çikolata kırıntıları',
    detailedDescription:
      'Beyaz çikolata bazlı, vanilya aromalı fildişi renkli kırıntılar. Açık renkli tatlı ve pastalar için görsel olarak ideal dekoratif kırıntı.',
    weight: ['500g', '1kg', '5kg'],
    usageArea: 'Dondurma, Cheesecake, Tatlı Yüzeyi, Dekor',
    highlights: ['Beyaz Çikolata', 'Fildişi Renk', 'Vanilya Aroması'],
    image: '/images/parça/kırıntı /fildişikırıntı.png',
    featured: true,
    seoDescription: 'Fildişi kırıntı çikolata, beyaz çikolata',
  },
];

export const ALL_PRODUCTS: Product[] = [
  ...KUVERTUR_PRODUCTS,
  ...DOLGU_GANAJ_PRODUCTS,
  ...SOS_PRODUCTS,
  ...DAMLA_CIKOLATA_PRODUCTS,
  ...VERMICELLI_PRODUCTS,
  ...PARCA_KIRINTI_PRODUCTS,
  ...DRAJELER_PRODUCTS,
  ...SPECIAL_PRODUCTS,
];

export const PRODUCTS_BY_CATEGORY: Record<CategoryKey, Product[]> = {
  kuvertur: KUVERTUR_PRODUCTS,
  'dolgu-ganaj': DOLGU_GANAJ_PRODUCTS,
  sos: SOS_PRODUCTS,
  'damla-cikolata': DAMLA_CIKOLATA_PRODUCTS,
  vermicelli: VERMICELLI_PRODUCTS,
  'parca-kirintı': PARCA_KIRINTI_PRODUCTS,
  drajeler: DRAJELER_PRODUCTS,
  special: SPECIAL_PRODUCTS,
};

export const FEATURED_PRODUCTS_CATALOG = ALL_PRODUCTS.filter((p) => p.featured);
